package base;

public class TestData {

    //Domain Site List
    public static String[] getDomainDropdownValues() {
        return new String[] {"00 Calibration Gateway", "00 Cosine"};
    }

    public static String[] getSuperAdminDropdownValues() {
        return new String[] {"Westford Solar", "Performance Test Unit", "Boston Calibration", "Mill Street", "Enginasion",
"Cass House", "New Bedford", "Greater Boston Food Bank", "Old Colony 1",
"Sierra CCD Grass Valley", "Leary House 2", "Jefferson Park", "BB&N School",
"Nexamp Peak- Hancock", "Sierra CCD Rocklin", "Lincoln Way", "300 Riverpark Drive Solar",
"ICOE (Imperial County Office of Education)", "St Polycarp 2 and 3",
"Hadley 2 Solar", "Sutton Solar", "Foster Solar", "Onset Water DIstrict",
"Factory Street Solar", "Athena Health", "Logee Street Solar", "Fitchburg Solar",
"PVMC, Halfmoon", "Golden Hills Solar", "Sampson Road Solar",
"Monson Solar", "Upton Solar", "Hatfield Renewables", "Theodore Drive Solar",
"Pleasantdale Road Solar", "Farley Road Solar", "New Braintree Solar",
"Webster Solar", "Canton Solar", "Belchertown Renewables (East)",
"Griffin Road Solar", "Berkshire School", "Amesbury Landfill", "Norton Landfill",
 "Tyngsborough Solar", "Agawam Landfill", "Falmouth", "Heritage Place",
"Osgood Solar", "00 Osgood Calibration", "00 Rachels Desk", "Waltham Solar",
"Ameresco Demo Unit", "Dudley Solar", "Peterson Road Solar",
"Rosebrook Farm", "Ajax", "Method Machine", "440 McClellan", "Aubuchon Hardware",
"Richmond Solar", "Redbrook Solar", "Cedar St Landfill Solar Project",
"Old Sturbridge Village", "Williamstown", "Dartmouth Farms Solar",
"Pleasant Street Solar", "Canton Solar 2", "Templeton Road Solar",
"Drydock 23", "00 Calibration Gateway", "Tantasqua Regional High School", "Genentech", "Simplex", "Belchertown Renewables (West)", "Terrapin Branch Solar",
"Sarah", "Four Oaks", "Nitro", "Princeton, NC", "Faison, NC", "Fairfield Ludlowe High School",
"NPS 1A", "South Robeson", "Progress 2", "Radiance 5", "Radiance 4", "2108 Albany",
"Cap City", "SES Navy Yard", "Pitkin", "NPS 4A", "Ashby 1 - North & Ashby 2 - South", "Academy of Hope", "Leicester High School", "Amherst 05325", "Pittsfield",
"Foster Renewables", "Coventry Solar","Newfield Solar",
                "Westminster Renewables South & North", "Burgess", "Franklin Solar",
                "Greeley-Weld Airport", "Macedon", "Anderson", "Cameo", "DIA 1", "DIA 2",
                "Linnebur", "Lowry", "McCormick", "Rifle", "Tebo 1", "Tebo 2", "Wiescamp",
        "Bennett", "Whittier", "Williamson", "Tanglewood Circle Solar 1",
                "Taconic High School", "Route 14A CDG - South & North", "Plainfield Solar",
                "South Mountain Company", "1890 Palmer", "Hoffmann - Bronx Sites",
                "Sun Farm V", "Sun Farm VI", "Bainbridge Solar",
                "Leesburg Solar", "Chester Woods Point Solar",
                "Hampton 1 Solar", "00 Cosine Test", "Wachusett Solar", "Soluga Farms IV",
                "Sadiebrook",  "Renew ABC", "Renew WMAC", "Renew WMDavis", "Hagerstown",
                "Robbinsville Solar (Robin MCK)", "Clarksville", "Guy-Perkins",
"Monte Vista 2","Sandy", "Freedom", "00 Cosine", "ER Verulamium",
 "Rock Creek 2", "Teterboro East", "Woodland Avenue Solar 1",
"Shiloh", "Chowan", "Equity", "Rexnord", "Alamosa Solar South",
"Solar Inventions", "Palmer Creek", "Day Hill", "Celina Solar",
"MLH 2", "NIPSCO 1 FIT - Goshen", "Lane", "20044 - Dos Palos Elementary School",
"20042 - Dos Palos High School", "20043 - Dos Palos Bryant Middle School",
 "McHattie (WO-1080583)", "North Carolina Solar 1", "Walker Hill", "Emory University - Gambrell Hall", "Lawrence Brook", "Electric City Solar North", "Electric City Solar South",
"Lincoln Farm",  "206 Cotton Mill", "Municipal Building", "Shelburne Museum",
"ER Salvage Yard", "Whately Renewables", "Las Virgenes", "Gliden (Op Zone)",
"Ryland (Op Zone)", "Windsor", "Valencia 3", "Valencia 2", "Amazon PSP1",
"Center Point", "GSPP Demonstration Site", "100 Phoenix", "Turquoise",
"371 Market Street", "Stuttgart City", "Forrest City Prison",
"Forrest City Eldridge Road", "SWWTP Hot Springs", "Deer Creek 2",
"Deer Creek 1",  "El Dorado Hills", "Phelps", "Bone Hill", "Billings Road",
"Graphite", "Lake Herman", "Severson Garden", "Bodega 1",
"Danville Solar, LLC", "Sunsense III Fletcher", "Amazon KSBD",
"P4Q", "Blue Prairie Solar", "Amazon SBD2", "Amazon LGB9", "Amazon OXR1",
"Bainbridge Expansion Gateway", "Amazon CMH4", "Amazon AKC1",
        "SUNY Albany", "SUNY Fredonia", "Center Road Solar", "Sand Hill Solar",
        "Tuusso-Penstemon", "Tuusso-Camas",  "Tuusso-Urtica (rev1)", "Amazon SBD1",
        "University at Buffalo Millersport", "University at Buffalo Bizer Creek",
        "University at Buffalo Creekside", "Amazon PCW1", "Strobus Solar", "DIA 7",
        "Stromland Solar", "Shamrock", "Hazel Solar", "Fountain Solar", "Rushford Village Solar",
        "Stockton Solar", "Friendship 1", "Buffalo Flats CO29", "Steamboat-Shelburne Museum",
        "Atkinson solar 2", "Lancaster", "ACT II Solar", "Smithfield I Solar", "Smithfield III Solar",
        "Amazon LAS1", "Park Street", "Main Street", "Dover", "Fair Haven", "Red Barn",
        "Westminster I", "Westminster II",  "Littleton", "North Smithfield", "Shirley",
        "154 / D. Fisher", "115 / G. Fisher", "Taunton", "Jericho",  "Palmer",  "Jackson Landfill",
        "Mt Arlington Landfill", "107 Chace Road", "Warren Harding ES",

                "David Brearley MSHS",
                "East Shore",
                "Kingston Water Treatment Plant",

                "DIA 8",
                "Little Pond Project",
                "Hodag Solar",
                "Ring Road",
                "Upland Road",
                "Jamesville Rd. Solar",
                "Mill Pond",
                "Bucknell University (ER Bison Solar)",
        "Worthington Woods",
        "Bogota BOE",
        "Fall River",
        "KIUC",
        "Technologics GW1",
        "Seneca",
        "West Brookfield",
        "Alton Road",
        "MTSun",
        "Amazon FAT2",
        "Friendship 2",
        "Joey's Sanctuary",
        "Randolph Gifford",
        "Hudson County Correctional Facility",
        "NHP4 - Anacostia Gardens",
        "Montezuma Solar",
        "Rocky Ford",
        "Totten Solar",
        "Maple City Solar",
        "Wilton Solar",
        "Amazon VGT1",
        "Ridgecrest",
        "Catholic Charities",
        "Broomfield - Muni Building",
        "WGBH Educational Foundation",
        "CU Boulder (fka CINC)",
        "Midway III",
        "NHP4 - Columbia Heights",
        "NHP4 - Roundtree",
        "Athens Ridge",
        "Richmond Hill",
        "Mars Hill",
        "Lincoln Solar",
        "Hartland GUVSWMD",
        "Andover Weston",
        "Royalton Post Farm",
        "St Johnsbury Lapierre",
        "Our Katahdin Solar",
        "Hog Bay Solar",
        "Phoenix",
        "PCIP",
        "Pittsford GLC Solar",
        "Sterling Community",
        "Grand Junction Mesa",
        "TVSD - ACES (Agua Caliente Elementary School)",
        "DIA",
        "DPS - South HS",
        "City Solar",
        "46 Precision",
        "Orlando Utilities Commission",
        "Cal Floyd Rd",
        "Camden",
        "Jeffrey Clark School",
        "Chester Solar",
        "Hartford Solar",
        "Sterling Correctional",
        "Novus Royalton Solar",
        "3030 30th St SE",
        "1070 Route 109 (BX Simply)",
        "University at Buffalo North Campus Roofs",
        "Quarter Horse",
        "Locke Brook Solar",
        "MLH 3",
        "Dan's Test Site",
        "Bladenboro 2",
        "Marinosci Law",
        "Appaloosa I",
        "Stanly",
        "NHP4 - Takoma Place",
        "Swamp Fox",
        "REI DC4",
        "SRC Brightridge",
        "Lutheran School Administration",
        "ER Pleasant Street Solar",
        "Sneads Grove Farm",
        "Hill Road Solar 1 (North)",
        "Hill Road Solar 2 (South)",
        "ER South ST Solar",
        "DIA 9",
        "Stockbridge",
        "Kosa",
        "Mahany",
        "Black Cat",
        "Pine Hill",
        "Albany 2",
        "Albany 1",
        "Upland",
        "Baker Rd. Phase 2",
        "Baker Rd. Phase 1",
        "Tyto Solar",
        "Georgetown-Polk Burnett",
        "Webster Creek-Oakdale 2",
        "Bluff Prairie-Vernon",
        "Barnet 5",
        "West Fairlee Stevens",
        "Topsham Solar",
        "Boothbay Solar",
        "Trimbelle-Pierce Pepin",
        "Wolf River-Chippewa Valley",
        "Popple Creek-Clark",
        "Walleye-Dunn 2",
        "Hay River-Dunn 1",
        "Ogema-Price",
        "Lemonweir-Oakdale 1",
        "Tully Solar 1",
        "Agrimony Solar 1",
        "Agrimony Solar 2",
        "Armstrong 1",
        "Lobelia Solar 1",
        "Tripple State",
        "Monday Farms",
        "West Salisbury",
        "Trent River",
        "Kalish",
        "Spring Valley 2",
        "Holstein",
        "Truman",
        "Woodland Church",
        "Lake City",
        "Morey Road",
        "Surrey Road",
        "Omohundro West",
        "Ledgeview Solar",
        "Oaks Landfill C",
        "Oaks Landfill A",
        "Oaks Landfill B",
        "Viaduct Solar",
        "TBD (former calibration gateway)",
        "Demonstration Site",
        "Cap City PCS",
        "00 Soiling Test",
        "SPI New Gateway",
        "Facile Solar",
        "Ballenger Garden",
        "Enstall Test Site NL",
        "Cal Floyd Rd",
        "Hyde Park Electric Dept",
        "Leeds Solar",
        "Overland Solar",
        "Robin Solar Farm",
        "Howell",
        "ER Alpine Street Solar",
        "00 Nifty Demo",
"ER Dairy Farm Solar LLC"
};
    }

    public static String[] getCompanyDropdownValues() {
        return new String[] {"00 Calibration Gateway", "00 Cosine"};
    }
}
